development:
  adapter: postgresql
  encoding: unicode
  database: databasename
  pool: 5
  username: <%= Rails.application.secrets.database_username %>
  password: <%= Rails.application.secrets.database_password %>
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: testdatabasename
  pool: 5
  username: <%= Rails.application.secrets.database_username %>
  password: <%= Rails.application.secrets.database_password %>
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: productiondatabasename
  pool: 5
  username: <%= Rails.application.secrets.database_username %>
  password: <%= Rails.application.secrets.database_password %>
  host: localhost
  port: 5432