development:
  adapter: sqlite3
  encoding: unicode
  database: databasename
  pool: 5
  username: postgres
  password: secret
  host: localhost
  port: 5432

test:
  adapter: sqlite3
  encoding: unicode
  database: testdatabasename
  pool: 5
  username: postgres
  password: secret
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: productiondatabasename
  pool: 5
  username: postgres
  password: secret
  host: localhost
  port: 5432