development:
  adapter: sqlite3
  encoding: unicode
  database: databasename
  pool: 5
  username: pedrobyd
  password: secret

test:
  adapter: sqlite3
  encoding: unicode
  database: testdatabasename
  pool: 5
  username: pedrobyd
  password: secret

production:
  adapter: postgresql
  encoding: unicode
  database: productiondatabasename
  pool: 5
  username: pedrobyd
  password: secret